//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSeguimiento.BussinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentos_prospectos
    {
        public int id_documento { get; set; }
        public int id_prospecto { get; set; }
        public string nombre_documento { get; set; }
        public byte[] documento { get; set; }
    }
}
